package workflowschema

import (
	"bytes"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var typescriptIdentifier = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// GenerateTypeScript emits the sole frontend workflow DTO and HTTP client
// authority from committed graph/API schemas.
func GenerateTypeScript(graphDocument, apiDocument []byte) ([]byte, error) {
	graphSchema, err := decodeDocument(graphDocument)
	if err != nil {
		return nil, fmt.Errorf("decode graph schema: %w", err)
	}
	apiSchema, err := decodeDocument(apiDocument)
	if err != nil {
		return nil, fmt.Errorf("decode API schema: %w", err)
	}
	definitions := make(map[string]any)
	for _, document := range []map[string]any{graphSchema, apiSchema} {
		current, _ := document["$defs"].(map[string]any)
		for name, value := range current {
			if _, exists := definitions[name]; exists {
				return nil, fmt.Errorf("duplicate TypeScript definition %q", name)
			}
			definitions[name] = value
		}
	}
	names := make([]string, 0, len(definitions))
	for name := range definitions {
		names = append(names, name)
	}
	sort.Strings(names)
	var output strings.Builder
	output.WriteString("// Code generated by go generate ./internal/api; DO NOT EDIT.\n")
	output.WriteString("// Source: committed workflow graph and HTTP API JSON Schemas.\n\n")
	fmt.Fprintf(&output, "export const WORKFLOW_API_SCHEMA = %s as const;\n", jsonLiteral(map[string]any{"id": apiSchema["$id"], "version": apiSchema["x-hadron-schema-version"]}))
	fmt.Fprintf(&output, "export const WORKFLOW_GRAPH_SCHEMA = %s as const;\n", jsonLiteral(apiSchema["x-hadron-graph-schema"]))
	fmt.Fprintf(&output, "export const WORKFLOW_AUTHORING_SCHEMA = %s as const;\n", jsonLiteral(apiSchema["x-hadron-authoring-schema"]))
	fmt.Fprintf(&output, "export const WORKFLOW_SOURCE_SCHEMA = %s as const;\n", jsonLiteral(apiSchema["x-hadron-workflow-source-schema"]))
	fmt.Fprintf(&output, "export const AGENT_AUTHORING_RESULT_SCHEMA = %s as const;\n", jsonLiteral(apiSchema["x-hadron-agent-result-schema"]))
	fmt.Fprintf(&output, "const WORKFLOW_GRAPH_SCHEMA_DOCUMENT: JSONSchema = %s;\n", jsonLiteral(graphSchema))
	fmt.Fprintf(&output, "const WORKFLOW_API_SCHEMA_DOCUMENT: JSONSchema = %s;\n\n", jsonLiteral(apiSchema))
	for _, name := range names {
		schema, _ := definitions[name].(map[string]any)
		writeDefinition(&output, name, schema)
		output.WriteByte('\n')
	}
	writeAuthoringDecoder(&output)
	writeClient(&output, apiSchema)
	return []byte(output.String()), nil
}

func writeAuthoringDecoder(output *strings.Builder) {
	output.WriteString(`export interface AuthoringDecodeLimits {
  maximum_bytes?: number;
  maximum_depth?: number;
  maximum_nodes?: number;
  maximum_edges?: number;
}

type JSONSchema = Record<string, unknown>;

// decodeAuthoringEnvelope is a generated, fail-closed client preflight. The
// service repeats these checks and performs ordinary compilation and policy.
export function decodeAuthoringEnvelope(input: unknown, limits: AuthoringDecodeLimits = {}): AuthoringEnvelope {
  const maximumBytes = authoringLimit(limits.maximum_bytes, 2 * 1024 * 1024, 'maximum_bytes');
  const maximumDepth = authoringLimit(limits.maximum_depth, 128, 'maximum_depth');
  const maximumNodes = authoringLimit(limits.maximum_nodes, 512, 'maximum_nodes');
  const maximumEdges = authoringLimit(limits.maximum_edges, 4096, 'maximum_edges');
  assertJSONSafe(input, maximumDepth, new Set<object>(), 0, '$');
  let encoded: string;
  try {
    encoded = JSON.stringify(input);
  } catch {
    throw new TypeError('authoring envelope must be JSON-serializable');
  }
  if (new TextEncoder().encode(encoded).byteLength > maximumBytes) {
    throw new TypeError('authoring envelope exceeds maximum_bytes');
  }
  const canonical: unknown = JSON.parse(encoded);
  validateJSONSchema(canonical, schemaDefinition(WORKFLOW_API_SCHEMA_DOCUMENT, 'AuthoringEnvelope'), WORKFLOW_API_SCHEMA_DOCUMENT, '$');
  const envelope = canonical as AuthoringEnvelope;
  if (envelope.schema_id !== WORKFLOW_AUTHORING_SCHEMA.id || envelope.schema_version !== WORKFLOW_AUTHORING_SCHEMA.version) {
    throw new TypeError('unsupported authoring envelope schema');
  }
  if (envelope.format === 'graph_ir') {
    if (envelope.material_schema_id !== WORKFLOW_GRAPH_SCHEMA.id || envelope.material_schema_version !== WORKFLOW_GRAPH_SCHEMA.version || !envelope.graph || envelope.source !== undefined) {
      throw new TypeError('unsupported graph IR material schema');
    }
    if (envelope.graph.nodes.length > maximumNodes || (envelope.graph.edges?.length ?? 0) > maximumEdges) {
      throw new TypeError('graph IR exceeds structural bounds');
    }
  } else if (envelope.format === 'workflow_source') {
    if (envelope.material_schema_id !== WORKFLOW_SOURCE_SCHEMA.id || envelope.material_schema_version !== WORKFLOW_SOURCE_SCHEMA.version || !envelope.source || envelope.graph !== undefined) {
      throw new TypeError('unsupported workflow source material schema');
    }
  } else {
    throw new TypeError('unsupported authoring material format');
  }
  return envelope;
}

function authoringLimit(value: number | undefined, fallback: number, name: string): number {
  if (value === undefined) return fallback;
  if (!Number.isFinite(value) || !Number.isSafeInteger(value) || value < 0) throw new TypeError(name + ' must be a finite nonnegative safe integer');
  return value;
}

export function createGraphAuthoringEnvelope(graph: WorkflowGraph): AuthoringEnvelope {
  return decodeAuthoringEnvelope({
    schema_id: WORKFLOW_AUTHORING_SCHEMA.id,
    schema_version: WORKFLOW_AUTHORING_SCHEMA.version,
    material_schema_id: WORKFLOW_GRAPH_SCHEMA.id,
    material_schema_version: WORKFLOW_GRAPH_SCHEMA.version,
    format: 'graph_ir',
    graph,
  });
}

export function createWorkflowSourceAuthoringEnvelope(source: string): AuthoringEnvelope {
  return decodeAuthoringEnvelope({
    schema_id: WORKFLOW_AUTHORING_SCHEMA.id,
    schema_version: WORKFLOW_AUTHORING_SCHEMA.version,
    material_schema_id: WORKFLOW_SOURCE_SCHEMA.id,
    material_schema_version: WORKFLOW_SOURCE_SCHEMA.version,
    format: 'workflow_source',
    source,
  });
}

function assertJSONSafe(value: unknown, maximum: number, seen: Set<object>, depth: number, path: string): void {
  if (value === null || typeof value === 'string' || typeof value === 'boolean') return;
  if (typeof value === 'number') {
    if (!Number.isFinite(value) || (Number.isInteger(value) && !Number.isSafeInteger(value))) throw new TypeError(path + ' must be a JSON-safe number');
    return;
  }
  if (typeof value !== 'object') throw new TypeError(path + ' must contain only JSON-safe values');
  if (seen.has(value)) throw new TypeError('authoring envelope must not contain cycles');
  if (depth + 1 > maximum) throw new TypeError('authoring envelope exceeds maximum_depth');
  seen.add(value);
  if (Array.isArray(value)) {
    if (Object.getPrototypeOf(value) !== Array.prototype) throw new TypeError(path + ' must be a plain JSON array');
    for (const key of Reflect.ownKeys(value)) {
      if (key === 'length') continue;
      if (typeof key !== 'string' || !/^(0|[1-9][0-9]*)$/.test(key) || Number(key) >= value.length) throw new TypeError(path + ' contains a non-JSON array property');
    }
    for (let index = 0; index < value.length; index++) {
      if (!Object.prototype.hasOwnProperty.call(value, index)) throw new TypeError(path + '[' + index + '] must not be a sparse array hole');
      const descriptor = Object.getOwnPropertyDescriptor(value, String(index));
      if (!descriptor || !descriptor.enumerable || !('value' in descriptor)) throw new TypeError(path + '[' + index + '] must be a plain JSON value');
      assertJSONSafe(descriptor.value, maximum, seen, depth + 1, path + '[' + index + ']');
    }
  } else {
    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) throw new TypeError(path + ' must be a plain JSON object');
    for (const key of Reflect.ownKeys(value)) {
      if (typeof key !== 'string') throw new TypeError(path + ' must not contain symbol keys');
      const descriptor = Object.getOwnPropertyDescriptor(value, key);
      if (!descriptor || !descriptor.enumerable || !('value' in descriptor)) throw new TypeError(path + '.' + key + ' must be a plain JSON value');
      assertJSONSafe(descriptor.value, maximum, seen, depth + 1, path + '.' + key);
    }
  }
  seen.delete(value);
}

function schemaDefinition(root: JSONSchema, name: string): JSONSchema {
  const definitions = root.$defs as Record<string, JSONSchema> | undefined;
  const schema = definitions?.[name];
  if (!schema) throw new TypeError('generated schema definition ' + name + ' is unavailable');
  return schema;
}

function resolveSchema(reference: string, root: JSONSchema): [JSONSchema, JSONSchema] {
  if (reference.startsWith(WORKFLOW_GRAPH_SCHEMA.id + '#/$defs/')) {
    const name = reference.slice(reference.lastIndexOf('/') + 1);
    return [schemaDefinition(WORKFLOW_GRAPH_SCHEMA_DOCUMENT, name), WORKFLOW_GRAPH_SCHEMA_DOCUMENT];
  }
  if (reference.startsWith('#/$defs/')) return [schemaDefinition(root, reference.slice(reference.lastIndexOf('/') + 1)), root];
  throw new TypeError('unsupported generated schema reference ' + reference);
}

function validateJSONSchema(value: unknown, schema: JSONSchema, root: JSONSchema, path: string): void {
  if (typeof schema.$ref === 'string') {
    const [resolved, resolvedRoot] = resolveSchema(schema.$ref, root);
    validateJSONSchema(value, resolved, resolvedRoot, path);
    return;
  }
  const alternatives = (schema.oneOf ?? schema.anyOf) as Array<JSONSchema> | undefined;
  if (alternatives) {
    if (!alternatives.some((candidate) => { try { validateJSONSchema(value, candidate, root, path); return true; } catch { return false; } })) {
      throw new TypeError(path + ' does not match the generated schema');
    }
    return;
  }
  const all = schema.allOf as Array<JSONSchema> | undefined;
  if (all) for (const candidate of all) validateJSONSchema(value, candidate, root, path);
  if (Array.isArray(schema.enum) && !schema.enum.some((candidate) => Object.is(candidate, value))) throw new TypeError(path + ' is not supported');
  const kind = schema.type;
  if (kind === 'object') {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) throw new TypeError(path + ' must be an object');
    const object = value as Record<string, unknown>;
    const properties = (schema.properties ?? {}) as Record<string, JSONSchema>;
    for (const required of (schema.required ?? []) as Array<string>) if (!(required in object)) throw new TypeError(path + '.' + required + ' is required');
    for (const [key, child] of Object.entries(object)) {
      if (properties[key]) validateJSONSchema(child, properties[key], root, path + '.' + key);
      else if (schema.additionalProperties === false) throw new TypeError(path + '.' + key + ' is unknown');
      else if (schema.additionalProperties && typeof schema.additionalProperties === 'object') validateJSONSchema(child, schema.additionalProperties as JSONSchema, root, path + '.' + key);
    }
  } else if (kind === 'array') {
    if (!Array.isArray(value)) throw new TypeError(path + ' must be an array');
    const items = schema.items as JSONSchema | undefined;
    if (items) value.forEach((child, index) => validateJSONSchema(child, items, root, path + '[' + index + ']'));
  } else if (kind === 'string' && typeof value !== 'string') throw new TypeError(path + ' must be a string');
  else if ((kind === 'integer' || kind === 'number') && (typeof value !== 'number' || !Number.isFinite(value) || (kind === 'integer' && !Number.isInteger(value)))) throw new TypeError(path + ' must be a ' + kind);
  else if (kind === 'boolean' && typeof value !== 'boolean') throw new TypeError(path + ' must be a boolean');
}

`)
}

func decodeDocument(data []byte) (map[string]any, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	var result map[string]any
	if err := decoder.Decode(&result); err != nil {
		return nil, err
	}
	return result, nil
}

func writeDefinition(output *strings.Builder, name string, schema map[string]any) {
	if schema["type"] == "object" {
		properties, hasProperties := schema["properties"].(map[string]any)
		if hasProperties && len(properties) != 0 {
			fmt.Fprintf(output, "export interface %s {\n", name)
			required := stringSet(schema["required"])
			names := make([]string, 0, len(properties))
			for field := range properties {
				names = append(names, field)
			}
			sort.Strings(names)
			for _, field := range names {
				property, _ := properties[field].(map[string]any)
				optional := "?"
				if required[field] {
					optional = ""
				}
				fmt.Fprintf(output, "  %s%s: %s;\n", typescriptProperty(field), optional, typeExpression(property))
			}
			if additional, ok := schema["additionalProperties"]; ok && additional != false {
				additionalSchema, _ := additional.(map[string]any)
				fmt.Fprintf(output, "  [key: string]: %s;\n", typeExpression(additionalSchema))
			}
			output.WriteString("}\n")
			return
		}
	}
	fmt.Fprintf(output, "export type %s = %s;\n", name, typeExpression(schema))
}

func typeExpression(schema map[string]any) string {
	if len(schema) == 0 {
		return "unknown"
	}
	if ref, ok := schema["$ref"].(string); ok {
		if at := strings.LastIndex(ref, "/"); at >= 0 {
			return ref[at+1:]
		}
	}
	if value, ok := schema["const"]; ok {
		return jsonLiteral(value)
	}
	if values, ok := schema["enum"].([]any); ok {
		parts := make([]string, len(values))
		for i, value := range values {
			parts[i] = jsonLiteral(value)
		}
		return strings.Join(parts, " | ")
	}
	for _, key := range []string{"oneOf", "anyOf"} {
		if values, ok := schema[key].([]any); ok {
			parts := make([]string, 0, len(values))
			for _, value := range values {
				current, _ := value.(map[string]any)
				parts = append(parts, typeExpression(current))
			}
			return strings.Join(parts, " | ")
		}
	}
	if values, ok := schema["allOf"].([]any); ok {
		parts := make([]string, 0, len(values))
		for _, value := range values {
			current, _ := value.(map[string]any)
			parts = append(parts, typeExpression(current))
		}
		return strings.Join(parts, " & ")
	}
	switch kind := schema["type"].(type) {
	case []any:
		parts := make([]string, 0, len(kind))
		for _, current := range kind {
			parts = append(parts, primitiveType(fmt.Sprint(current), schema))
		}
		return strings.Join(parts, " | ")
	case string:
		return primitiveType(kind, schema)
	default:
		return "unknown"
	}
}

func primitiveType(kind string, schema map[string]any) string {
	switch kind {
	case "null":
		return "null"
	case "boolean":
		return "boolean"
	case "integer", "number":
		return "number"
	case "string":
		return "string"
	case "array":
		items, _ := schema["items"].(map[string]any)
		return "Array<" + typeExpression(items) + ">"
	case "object":
		if properties, ok := schema["properties"].(map[string]any); ok && len(properties) != 0 {
			required := stringSet(schema["required"])
			names := make([]string, 0, len(properties))
			for name := range properties {
				names = append(names, name)
			}
			sort.Strings(names)
			parts := make([]string, 0, len(names))
			for _, name := range names {
				current, _ := properties[name].(map[string]any)
				suffix := "?"
				if required[name] {
					suffix = ""
				}
				parts = append(parts, typescriptProperty(name)+suffix+": "+typeExpression(current))
			}
			return "{ " + strings.Join(parts, "; ") + " }"
		}
		if additional, ok := schema["additionalProperties"].(map[string]any); ok {
			return "Record<string, " + typeExpression(additional) + ">"
		}
		return "Record<string, unknown>"
	default:
		return "unknown"
	}
}

func writeClient(output *strings.Builder, document map[string]any) {
	output.WriteString("export type WorkflowTransport = <T>(path: string, init: RequestInit) => Promise<T>;\n\n")
	output.WriteString("export class HadronWorkflowClient {\n  constructor(private readonly transport: WorkflowTransport) {}\n\n")
	operations, _ := document["x-hadron-operations"].([]any)
	for _, raw := range operations {
		value, _ := raw.(map[string]any)
		name, _ := value["name"].(string)
		request, _ := value["request"].(string)
		response, _ := value["response"].(string)
		path, _ := value["path"].(string)
		pathField, _ := value["path_field"].(string)
		idempotency, _ := value["idempotency_key"].(string)
		fmt.Fprintf(output, "  %s(request: %s): Promise<%s> {\n", name, request, response)
		pathExpression := strconv.Quote(path)
		if pathField != "" {
			pathExpression = "`" + strings.ReplaceAll(path, "{"+pathField+"}", "${encodeURIComponent(String(request."+pathField+"))}") + "`"
		}
		fmt.Fprintf(output, "    return this.transport<%s>(%s, {\n      method: %s,\n", response, pathExpression, strconv.Quote(fmt.Sprint(value["method"])))
		if idempotency != "" {
			fmt.Fprintf(output, "      headers: { 'Idempotency-Key': String(request.%s) },\n", idempotency)
		}
		output.WriteString("      body: JSON.stringify(request),\n    });\n  }\n\n")
	}
	output.WriteString("}\n")
}

func stringSet(input any) map[string]bool {
	result := make(map[string]bool)
	values, _ := input.([]any)
	for _, value := range values {
		result[fmt.Sprint(value)] = true
	}
	return result
}
func typescriptProperty(input string) string {
	if typescriptIdentifier.MatchString(input) {
		return input
	}
	return strconv.Quote(input)
}
func jsonLiteral(input any) string { encoded, _ := json.Marshal(input); return string(encoded) }
