// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveBlueprintFile(arg1) {
  return window['go']['main']['App']['ArchiveBlueprintFile'](arg1);
}

export function CopyBlueprintFile(arg1, arg2) {
  return window['go']['main']['App']['CopyBlueprintFile'](arg1, arg2);
}

export function CreateBlueprintFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBlueprintFile'](arg1, arg2, arg3);
}

export function CreateDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateDirectory'](arg1, arg2);
}

export function DeleteBlueprintFile(arg1) {
  return window['go']['main']['App']['DeleteBlueprintFile'](arg1);
}

export function DeleteTelemetryLog(arg1) {
  return window['go']['main']['App']['DeleteTelemetryLog'](arg1);
}

export function GetBlueprintDir() {
  return window['go']['main']['App']['GetBlueprintDir']();
}

export function GetBlueprintMetadata(arg1) {
  return window['go']['main']['App']['GetBlueprintMetadata'](arg1);
}

export function GetDaemonAddr() {
  return window['go']['main']['App']['GetDaemonAddr']();
}

export function GetDaemonStatus() {
  return window['go']['main']['App']['GetDaemonStatus']();
}

export function GetPreference(arg1) {
  return window['go']['main']['App']['GetPreference'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListFilesInDir(arg1) {
  return window['go']['main']['App']['ListFilesInDir'](arg1);
}

export function ListTelemetryRuns() {
  return window['go']['main']['App']['ListTelemetryRuns']();
}

export function MoveBlueprintFile(arg1, arg2) {
  return window['go']['main']['App']['MoveBlueprintFile'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function ParseBlueprintFull(arg1) {
  return window['go']['main']['App']['ParseBlueprintFull'](arg1);
}

export function ParseBlueprintInputs(arg1) {
  return window['go']['main']['App']['ParseBlueprintInputs'](arg1);
}

export function ReadBlueprintFile(arg1) {
  return window['go']['main']['App']['ReadBlueprintFile'](arg1);
}

export function ReadTelemetryLog(arg1) {
  return window['go']['main']['App']['ReadTelemetryLog'](arg1);
}

export function SaveBlueprintFile(arg1, arg2) {
  return window['go']['main']['App']['SaveBlueprintFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectBlueprintFile() {
  return window['go']['main']['App']['SelectBlueprintFile']();
}

export function SelectDirectoryDialog() {
  return window['go']['main']['App']['SelectDirectoryDialog']();
}

export function SetBlueprintDir(arg1) {
  return window['go']['main']['App']['SetBlueprintDir'](arg1);
}

export function SetPreference(arg1, arg2) {
  return window['go']['main']['App']['SetPreference'](arg1, arg2);
}

export function ValidateBlueprintFile(arg1) {
  return window['go']['main']['App']['ValidateBlueprintFile'](arg1);
}
