// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ArchiveBlueprintFile(arg1:string):Promise<void>;

export function CopyBlueprintFile(arg1:string,arg2:string):Promise<string>;

export function CreateBlueprintFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateDirectory(arg1:string,arg2:string):Promise<string>;

export function DeleteBlueprintFile(arg1:string):Promise<void>;

export function DeleteTelemetryLog(arg1:string):Promise<void>;

export function GetBlueprintMetadata(arg1:string):Promise<string>;

export function GetDaemonAddr():Promise<string>;

export function GetDaemonStatus():Promise<string>;

export function GetPreference(arg1:string):Promise<string>;

export function GetSettings():Promise<string>;

export function ListFilesInDir(arg1:string):Promise<Array<main.FileEntry>>;

export function ListTelemetryRuns():Promise<string>;

export function MoveBlueprintFile(arg1:string,arg2:string):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function ParseBlueprintFull(arg1:string):Promise<string>;

export function ParseBlueprintInputs(arg1:string):Promise<Array<main.BlueprintInput>>;

export function ReadBlueprintFile(arg1:string):Promise<string>;

export function ReadTelemetryLog(arg1:string):Promise<string>;

export function SaveBlueprintFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SelectBlueprintFile():Promise<string>;

export function SelectDirectoryDialog():Promise<string>;

export function SetPreference(arg1:string,arg2:string):Promise<void>;

export function ValidateBlueprintFile(arg1:string):Promise<main.ValidateResult>;
